### ISSUE TITLE
Rule discussion - JSX not allowed in files with extension '.js'

### ISSUE THREAD

**Issue by wcardosodev** [statsbomb/eslint-config-statsbomb#3]
At the moment in the Gatekeeper project all the files are using the `.js` extension, including the ones with JSX. 

I guess this comes down to personal opinion but would be good to discuss the pro's and con's of having the rule versus not having it. 

[Discussion of the rule from the airbnb github](https://github.com/airbnb/javascript/pull/985)

**Comment by yodaddyp** [comment]
Personally, I like having the `jsx` extension just because it's easy to spot in the file system your React components and easily distinguish them from regular javascript; helpers, utils, reducers etc.

That said I don't feel strongly one way or another on this particular rule so I am happy with going with the consensus. Perhaps this is a valid rule to disable on maturer systems where there is no perceived benefit and lots of effort (? - depends on the file structure) I am assuming it's not an easy task on gatekeeper to just rename them?

**Comment by wcardosodev** [comment]
In Gatekeeper, generally the helper or util files have their own folders such as `util/array.js` so can be distinguished that way, but I do agree that does make it even more clear.

I'm also happy with either decision to be honest, but yes there is a fair few files on Gatekeeper where I'd rather just disable the rule unless necessary to keep it on.
